name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint:md
      - uses: actions/cache@v2
        id: lint-cache
        with:
          path: '.eslintcache'
          key: ${{ runner.os }}-lint-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-
        if: always()
      - run: yarn lint:ts
        if: always()
      - run: yarn lint:versions
        if: always()

