name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g group-dependencies
      - run: deps install lint
      - run: yarn lint:md
      - run: yarn lint:ts
      - run: yarn lint:versions

