name: lint
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g install-subset
      - run: subset install lint
      - run: yarn lint:md
      - run: yarn lint:ts
      - run: yarn lint:versions

